CREATE DATABASE M_InLock;
USE M_InLock;
CREATE TABLE Estudios
(
	IdEstudio INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	DataCriacao DATE NOT NULL,
	IdUsuario INT FOREIGN KEY REFERENCES Usuarios(IdUsuario),
	PaisOrigem VARCHAR(255) NOT NULL
);
CREATE TABLE Jogos
(
	IdJogo INT PRIMARY KEY IDENTITY,
	Nome VARCHAR(100) NOT NULL,
	DataLancamento DATE NOT NULL,
	Valor SMALLMONEY NOT NULL,
	IdEstudio INT FOREIGN KEY REFERENCES Estudios(IdEstudio)
);
CREATE TABLE Usuarios
(
	IdUsuario INT PRIMARY KEY IDENTITY,
	Email VARCHAR(255) NOT NULL,
	Senha VARCHAR(255) NOT NULL,
	Permissao BIT NOT NULL
);
